/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unity_kernel_engine_zorba_UnityZorbaDynamicContext */

#ifndef _Included_unity_kernel_engine_zorba_UnityZorbaDynamicContext
#define _Included_unity_kernel_engine_zorba_UnityZorbaDynamicContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     unity_kernel_engine_zorba_UnityZorbaDynamicContext
 * Method:    addExternalFunctionParameter
 * Signature: (Ljava/lang/String;Ljava/lang/AutoCloseable;)V
 */
JNIEXPORT void JNICALL Java_unity_kernel_engine_zorba_UnityZorbaDynamicContext_addExternalFunctionParameter
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     unity_kernel_engine_zorba_UnityZorbaDynamicContext
 * Method:    getExternalFunctionParameter
 * Signature: (Ljava/lang/String;)Ljava/lang/AutoCloseable;
 */
JNIEXPORT jobject JNICALL Java_unity_kernel_engine_zorba_UnityZorbaDynamicContext_getExternalFunctionParameter
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
