/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unity_kernel_engine_UnityAnalyticsEngineManager */

#ifndef _Included_unity_kernel_engine_UnityAnalyticsEngineManager
#define _Included_unity_kernel_engine_UnityAnalyticsEngineManager
#ifdef __cplusplus
extern "C" {
#endif
#undef unity_kernel_engine_UnityAnalyticsEngineManager_DEBUG
#define unity_kernel_engine_UnityAnalyticsEngineManager_DEBUG 0L
/*
 * Class:     unity_kernel_engine_UnityAnalyticsEngineManager
 * Method:    Py_Finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_unity_kernel_engine_UnityAnalyticsEngineManager_Py_1Finalize
  (JNIEnv *, jobject);

/*
 * Class:     unity_kernel_engine_UnityAnalyticsEngineManager
 * Method:    Py_Initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_unity_kernel_engine_UnityAnalyticsEngineManager_Py_1Initialize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
